/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jedisto_rncrypto_RNCryptoJni */

#ifndef _Included_cn_jedisto_rncrypto_RNCryptoJni
#define _Included_cn_jedisto_rncrypto_RNCryptoJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jedisto_rncrypto_RNCryptoJni
 * Method:    randomBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jedisto_rncrypto_RNCryptoJni_randomBytes
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
