/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jedisto_rncrypto_RNCryptoJni */

#ifndef _Included_cn_jedisto_rncrypto_RNCryptoJni
#define _Included_cn_jedisto_rncrypto_RNCryptoJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jedisto_rncrypto_RNCryptoJni
 * Method:    randomBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jedisto_rncrypto_RNCryptoJni_randomBytes
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_jedisto_rncrypto_RNCryptoJni
 * Method:    eccGenerateKeys
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_cn_jedisto_rncrypto_RNCryptoJni_eccGenerateKeys
  (JNIEnv *, jclass);

/*
 * Class:     cn_jedisto_rncrypto_RNCryptoJni
 * Method:    eccEncrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jedisto_rncrypto_RNCryptoJni_eccEncrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     cn_jedisto_rncrypto_RNCryptoJni
 * Method:    eccDecrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jedisto_rncrypto_RNCryptoJni_eccDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
